# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - python-test-2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Determine Python dependency file
        id: detect_install_file
        run: |
          if [ -f "setup.py" ]; then
            echo "Found setup.py based package installation"
            echo "install_type=setup" >> $GITHUB_OUTPUT
          elif [ -f "requirements.txt" ]; then
            echo "Found requirements.txt based package installation"
            echo "install_type=requirements" >> $GITHUB_OUTPUT
          elif [ -f "pyproject.toml" ]; then
            echo "Found pyproject.toml based package installation"
            echo "install_type=pyproject" >> $GITHUB_OUTPUT
          else
            echo "install_type=none" >> $GITHUB_OUTPUT
          fi

      - name: Create and Start virtual environment and Install Dependencies
        if: ${{ steps.detect_install_file.outputs.install_type != 'none' }}
        run: |
          python -m venv antenv
          source antenv/bin/activate
          case "${{ steps.check_file.outputs.install_type }}" in
            setup)
              pip install .
              ;;
            requirements)
              pip install -r requirements.txt
              ;;
            pyproject)
              pip install .
              ;;
          esac

      # - name: Create and start virtual environment
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate
      
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FFDA7E92848D4F28B44BB48A55733BDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_140C7F2F827A49DA9EED7FCFDA84A075 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8ADE70E0E9AC43EF949A698C6E8FE539 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'python-test-2'
          slot-name: 'Production'

          

