# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - release-python

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
      
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
 
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D25D65CD4AE24F698FBE429AEDF8A050 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B11F0CCE8845415EB4BA9257CCB3A907 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3326C3F838FF4A75ADA80A0FE8429754 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@releases/v3-fix-all-linux-apps
        id: deploy-to-webapp
        with:
          app-name: 'release-python'
          slot-name: 'Production'

# jobs:
#  build-and-deploy:
#   runs-on: ubuntu-latest
#   permissions:
#     id-token: write #This is required for requesting the JWT
#     contents: read #This is required for actions/checkout
#   steps:
#   # checkout the repo 
#   - uses: actions/checkout@v3
#   # setup python
#   - name: Setup Python
#     uses: actions/setup-python@v1
#     with:
#      python-version: '3.12'
#   # install dependencies
#   - name: Create and start virtual environment
#     working-directory: .
#     run: |
#      python -m venv --copies antenv
#      source antenv/bin/activate
#      pip install setuptools
#      pip install -r requirements.txt
#   # Azure login
#   - name: Login to Azure
#     uses: azure/login@v2
#     with:
#       client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D25D65CD4AE24F698FBE429AEDF8A050 }}
#       tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B11F0CCE8845415EB4BA9257CCB3A907 }}
#       subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3326C3F838FF4A75ADA80A0FE8429754 }}
#   # deploy web app
#   - uses: azure/webapps-deploy@v2
#     with:
#      app-name: 'release-python'
#   # Azure logout
#   - name: logout
#     run: |
#      az logout
          
